#主
spring:
  master:
    datasource:
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: ******
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
#从
  slave:
    datasource:
      jdbcUrl: jdbc:mysql://localhost:3306/web17?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: ******

#spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create
